name: .NET Nuget Publish

on:
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore src/Cosmic.Allocator/Cosmic.Allocator.csproj

    - name: Build project
      run: dotnet build src/Cosmic.Allocator/Cosmic.Allocator.csproj --configuration Release

    - name: Pack NuGet package
      run: dotnet pack src/Cosmic.Allocator/Cosmic.Allocator.csproj --configuration Release --output ./nupkgs
      
    - name: Publish to NuGet
      run: dotnet nuget push **/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate